import { library, config } from "@fortawesome/fontawesome-svg-core";
import { faBorderAll, faList } from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;
library.add(faList, faBorderAll);

import "@fortawesome/fontawesome-svg-core/styles.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "styles/index.scss";
import "styles/globals.css";
import Head from "next/head";
import Layout from "components/layout/Layout";
import { createStore, combineReducers } from "redux";
import { Provider } from "react-redux";
import allReducers from "components/learn/reducers";

const store = createStore(
  allReducers
  //window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

//store.subscribe(() => console.log(store.getState()));

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Adithya Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Provider>
    </div>
  );
}

export default MyApp;
